.PHONY: update

##########
# Update #
##########

## Update environment
update: export ANSIBLE_TAGS = manala.update
update:
	$(call log,Vagrant provision...)
	@vagrant provision

## Update ansible
update-ansible: export ANSIBLE_TAGS = manala.update
update-ansible:
	$(call log,Vagrant provision...)
	@vagrant provision --provision-with ansible
