.PHONY: setup

#########
# Setup #
#########

## Setup environment & Install & Build application
setup:
	$(call log,Vagrant up...)
	@vagrant up --no-provision

	$(call log,Vagrant provision...)
	@vagrant provision
	
	$(call log,Make install & build...)
	@vagrant ssh -- "cd /srv/app && make install build"
